# Generated by Django 4.2.23 on 2025-06-25 15:27
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-score']},
        ),
    ]
