# Generated by Django 4.2.23 on 2025-06-25 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_alter_recommendation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
